# Site settings
title: Spirals Team - Job/Intership offers
description: A blog about job and internship offers
# baseurl: "/jobs" # the subpath of your site, e.g. /blog
url: "http://spirals-team.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Spirals Team
user_description: Inria / Univ. Lille research group
email: spirals-recrute@inria.fr
twitter_username: SpiralsTeam
github_username:  Spirals-Team
#gplus_username:  lorem_ipsum
#disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Us
    url: http://team.inria.fr/spirals

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
